FROM php:7.4-apache
#ENV TZ="America/Lima"

RUN apt-get update

RUN pecl install xdebug-2.9.0 && docker-php-ext-enable xdebug
RUN docker-php-ext-install mysqli pdo pdo_mysql

RUN a2enmod rewrite

# COMPOSER 
RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer

RUN apt-get install -y sudo git npm vim && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*

# USER
#ARG USERNAME=nonroot
#ARG PASSWORD=nonroot
#ARG USER_UID=1000
#ARG USER_GID=$USER_UID
#RUN groupadd --gid $USER_GID $USERNAME && useradd --uid $USER_UID --gid $USER_GID -s /bin/bash -g $USER_GID -m $USERNAME && usermod -aG sudo $USERNAME && echo "$USERNAME:$PASSWORD" | chpasswd

# USER $USERNAME
